### ISSUE TITLE
fix aside position

### ISSUE THREAD

**Issue by adekimpianna** [harunaltunhr/integrate-week2#11]
the position of aside is too much to the bottom. is there a way to fix it?
suggested solutions, you can try both:
* move element `aside` after the `section` and before `article` 
* create one div including article and section after that aside elements will be top

![image](https://user-images.githubusercontent.com/62487749/83245002-73ed6b00-a1a0-11ea-9a75-a7b1e8f48a2e.png)
i think the paragraph "Would you like to see...." is double? 😄

**Comment by miroslavveljanoski** [comment]
@adekimpianna I will try to fix this.
