### ISSUE TITLE
Create aside

### ISSUE THREAD

**Issue by harunaltunhr** [harunaltunhr/integrate-week2#3]

**Comment by adekimpianna** [comment]
Aside Text: (35%)
Visit Brussels on our Choco Tour!
Would you like to see Brussels in a different way and discover the secrets of chocolate? Why not join our Planète Chocolat Tour ? A different kind of tour that will take you to Manneken Pis, the Grand-Place and some of the other sights that make this European capital so famous. Contact them https://www.planetechocolat.com/en/content/16-visit-brussels-choco-tour

**Comment by adekimpianna** [comment]
Edit  
@miroslavveljanoski can you please change the aside text to 30%, I missed calculated
