### ISSUE TITLE
revision for nav and footer

### ISSUE THREAD

**Issue by adekimpianna** [harunaltunhr/integrate-week2#8]
@harunaltunhr sorry, whren i turn the page into live, i can see what is missing. you already made styles for nav and footer:

![image](https://user-images.githubusercontent.com/62487749/83232224-1ac80c00-a18d-11ea-9620-14ddfc0c05f9.png)

but it does not show on the live page. any idea why?

![image](https://user-images.githubusercontent.com/62487749/83230860-cde33600-a18a-11ea-9cd4-1e71d41ad780.png)

**Comment by harunaltunhr** [comment]
Because, when you merge branch, for resolving conflict, you change index. html wrongly. You add <nav> part in <header>, so style will not work. I will fix right now

**Comment by adekimpianna** [comment]
sorry, that is the
